//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoldenEggNest
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyPrice
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public double ClosingPrice { get; set; }
        public int InstrumentId { get; set; }
    
        public virtual Instrument Instrument { get; set; }
    }
}
