//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monte_Carlo_6._1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instrument
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Instrument()
        {
            this.Trades = new HashSet<Trade>();
        }
    
        public int Id { get; set; }
        public string CompanyName { get; set; }
        public string Ticker { get; set; }
        public string Exchange { get; set; }
        public double Strike { get; set; }
        public double Tenor { get; set; }
        public Nullable<bool> IsCall { get; set; }
        public int InstTypeId { get; set; }
        public Nullable<double> Barrier { get; set; }
        public Nullable<double> Rebate { get; set; }
        public int PriceId { get; set; }
    
        public virtual InstType InstType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trade> Trades { get; set; }
        public virtual Price Price { get; set; }
    }
}
