//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monte_Carlo_6._1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Portfolio_x0020_ManagerContainer : DbContext
    {
        public Portfolio_x0020_ManagerContainer()
            : base("name=Portfolio_x0020_ManagerContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Instrument> Instruments { get; set; }
        public virtual DbSet<Price> Prices { get; set; }
        public virtual DbSet<Trade> Trades { get; set; }
        public virtual DbSet<InterestRate> InterestRates { get; set; }
        public virtual DbSet<InstType> InstTypes { get; set; }
    }
}
